// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0

package sqlitestore

type Alias struct {
	ID          string
	Name        string
	Command     string
	Description string
	Enabled     int64
	Platforms   string
	Shells      string
	Tags        string
	CreatedAt   string
	UpdatedAt   string
}

type AliasDevice struct {
	AliasID  string
	DeviceID string
}

type AliasProfile struct {
	AliasID   string
	ProfileID string
}

type Device struct {
	ID            string
	Name          string
	Platform      string
	Shell         string
	ClientVersion string
	CreatedAt     string
	UpdatedAt     string
	LastSeenAt    *string
	LastSyncAt    *string
	RevokedAt     *string
}

type DeviceProfile struct {
	DeviceID  string
	ProfileID string
}

type Operator struct {
	ID           string
	Username     string
	PasswordHash string
	CreatedAt    string
	UpdatedAt    string
}

type Profile struct {
	ID          string
	Name        string
	Description string
	CreatedAt   string
	UpdatedAt   string
}

type Token struct {
	ID         string
	Kind       string
	SubjectID  string
	Lookup     string
	SecretHash []byte
	ProfileIds string
	CreatedAt  string
	ExpiresAt  *string
	UsedAt     *string
	RevokedAt  *string
}
