// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0
// source: query.sql

package sqlitestore

import (
	"context"
)

const clearAliasDevices = `-- name: ClearAliasDevices :exec
DELETE FROM alias_devices WHERE alias_id = ?
`

func (q *Queries) ClearAliasDevices(ctx context.Context, aliasID string) error {
	_, err := q.db.ExecContext(ctx, clearAliasDevices, aliasID)
	return err
}

const clearAliasProfiles = `-- name: ClearAliasProfiles :exec
DELETE FROM alias_profiles WHERE alias_id = ?
`

func (q *Queries) ClearAliasProfiles(ctx context.Context, aliasID string) error {
	_, err := q.db.ExecContext(ctx, clearAliasProfiles, aliasID)
	return err
}

const clearDeviceProfiles = `-- name: ClearDeviceProfiles :exec
DELETE FROM device_profiles WHERE device_id = ?
`

func (q *Queries) ClearDeviceProfiles(ctx context.Context, deviceID string) error {
	_, err := q.db.ExecContext(ctx, clearDeviceProfiles, deviceID)
	return err
}

const consumeEnrollmentToken = `-- name: ConsumeEnrollmentToken :execrows
UPDATE tokens
SET used_at = ?, subject_id = ?
WHERE lookup = ? AND kind = 'enrollment' AND used_at IS NULL AND revoked_at IS NULL
  AND (expires_at IS NULL OR expires_at > ?)
`

type ConsumeEnrollmentTokenParams struct {
	UsedAt    *string
	SubjectID string
	Lookup    string
	ExpiresAt *string
}

func (q *Queries) ConsumeEnrollmentToken(ctx context.Context, arg ConsumeEnrollmentTokenParams) (int64, error) {
	result, err := q.db.ExecContext(ctx, consumeEnrollmentToken,
		arg.UsedAt,
		arg.SubjectID,
		arg.Lookup,
		arg.ExpiresAt,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const countOperators = `-- name: CountOperators :one
SELECT COUNT(*) FROM operators
`

func (q *Queries) CountOperators(ctx context.Context) (int64, error) {
	row := q.db.QueryRowContext(ctx, countOperators)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createAlias = `-- name: CreateAlias :one

INSERT INTO aliases (id, name, command, description, enabled, platforms, shells, tags, created_at, updated_at)
VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?)
RETURNING id, name, command, description, enabled, platforms, shells, tags, created_at, updated_at
`

type CreateAliasParams struct {
	ID          string
	Name        string
	Command     string
	Description string
	Enabled     int64
	Platforms   string
	Shells      string
	Tags        string
	CreatedAt   string
	UpdatedAt   string
}

// Queries for internal/store/sqlitestore, generated into this package by
// sqlc (design decision 6). Every statement is parameterized; sqlc never
// concatenates values into SQL text (threat matrix: SQL construction).
func (q *Queries) CreateAlias(ctx context.Context, arg CreateAliasParams) (Alias, error) {
	row := q.db.QueryRowContext(ctx, createAlias,
		arg.ID,
		arg.Name,
		arg.Command,
		arg.Description,
		arg.Enabled,
		arg.Platforms,
		arg.Shells,
		arg.Tags,
		arg.CreatedAt,
		arg.UpdatedAt,
	)
	var i Alias
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Command,
		&i.Description,
		&i.Enabled,
		&i.Platforms,
		&i.Shells,
		&i.Tags,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const createOperator = `-- name: CreateOperator :one
INSERT INTO operators (id, username, password_hash, created_at, updated_at)
VALUES (?, ?, ?, ?, ?)
RETURNING id, username, password_hash, created_at, updated_at
`

type CreateOperatorParams struct {
	ID           string
	Username     string
	PasswordHash string
	CreatedAt    string
	UpdatedAt    string
}

func (q *Queries) CreateOperator(ctx context.Context, arg CreateOperatorParams) (Operator, error) {
	row := q.db.QueryRowContext(ctx, createOperator,
		arg.ID,
		arg.Username,
		arg.PasswordHash,
		arg.CreatedAt,
		arg.UpdatedAt,
	)
	var i Operator
	err := row.Scan(
		&i.ID,
		&i.Username,
		&i.PasswordHash,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const createProfile = `-- name: CreateProfile :one
INSERT INTO profiles (id, name, description, created_at, updated_at)
VALUES (?, ?, ?, ?, ?)
RETURNING id, name, description, created_at, updated_at
`

type CreateProfileParams struct {
	ID          string
	Name        string
	Description string
	CreatedAt   string
	UpdatedAt   string
}

func (q *Queries) CreateProfile(ctx context.Context, arg CreateProfileParams) (Profile, error) {
	row := q.db.QueryRowContext(ctx, createProfile,
		arg.ID,
		arg.Name,
		arg.Description,
		arg.CreatedAt,
		arg.UpdatedAt,
	)
	var i Profile
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Description,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const createToken = `-- name: CreateToken :exec
INSERT INTO tokens (id, kind, subject_id, lookup, secret_hash, profile_ids, created_at, expires_at, used_at, revoked_at)
VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?)
`

type CreateTokenParams struct {
	ID         string
	Kind       string
	SubjectID  string
	Lookup     string
	SecretHash []byte
	ProfileIds string
	CreatedAt  string
	ExpiresAt  *string
	UsedAt     *string
	RevokedAt  *string
}

func (q *Queries) CreateToken(ctx context.Context, arg CreateTokenParams) error {
	_, err := q.db.ExecContext(ctx, createToken,
		arg.ID,
		arg.Kind,
		arg.SubjectID,
		arg.Lookup,
		arg.SecretHash,
		arg.ProfileIds,
		arg.CreatedAt,
		arg.ExpiresAt,
		arg.UsedAt,
		arg.RevokedAt,
	)
	return err
}

const deleteAlias = `-- name: DeleteAlias :execrows
DELETE FROM aliases WHERE id = ?
`

func (q *Queries) DeleteAlias(ctx context.Context, id string) (int64, error) {
	result, err := q.db.ExecContext(ctx, deleteAlias, id)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const deleteDevice = `-- name: DeleteDevice :execrows
DELETE FROM devices WHERE id = ?
`

func (q *Queries) DeleteDevice(ctx context.Context, id string) (int64, error) {
	result, err := q.db.ExecContext(ctx, deleteDevice, id)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const deleteProfile = `-- name: DeleteProfile :execrows
DELETE FROM profiles WHERE id = ?
`

func (q *Queries) DeleteProfile(ctx context.Context, id string) (int64, error) {
	result, err := q.db.ExecContext(ctx, deleteProfile, id)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const getAlias = `-- name: GetAlias :one
SELECT id, name, command, description, enabled, platforms, shells, tags, created_at, updated_at
FROM aliases WHERE id = ?
`

func (q *Queries) GetAlias(ctx context.Context, id string) (Alias, error) {
	row := q.db.QueryRowContext(ctx, getAlias, id)
	var i Alias
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Command,
		&i.Description,
		&i.Enabled,
		&i.Platforms,
		&i.Shells,
		&i.Tags,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getDevice = `-- name: GetDevice :one
SELECT id, name, platform, shell, client_version, created_at, updated_at, last_seen_at, last_sync_at, revoked_at
FROM devices WHERE id = ?
`

func (q *Queries) GetDevice(ctx context.Context, id string) (Device, error) {
	row := q.db.QueryRowContext(ctx, getDevice, id)
	var i Device
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Platform,
		&i.Shell,
		&i.ClientVersion,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.LastSeenAt,
		&i.LastSyncAt,
		&i.RevokedAt,
	)
	return i, err
}

const getOperator = `-- name: GetOperator :one
SELECT id, username, password_hash, created_at, updated_at FROM operators WHERE id = ?
`

func (q *Queries) GetOperator(ctx context.Context, id string) (Operator, error) {
	row := q.db.QueryRowContext(ctx, getOperator, id)
	var i Operator
	err := row.Scan(
		&i.ID,
		&i.Username,
		&i.PasswordHash,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getOperatorByUsername = `-- name: GetOperatorByUsername :one
SELECT id, username, password_hash, created_at, updated_at FROM operators WHERE username = ?
`

func (q *Queries) GetOperatorByUsername(ctx context.Context, username string) (Operator, error) {
	row := q.db.QueryRowContext(ctx, getOperatorByUsername, username)
	var i Operator
	err := row.Scan(
		&i.ID,
		&i.Username,
		&i.PasswordHash,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getProfile = `-- name: GetProfile :one
SELECT id, name, description, created_at, updated_at FROM profiles WHERE id = ?
`

func (q *Queries) GetProfile(ctx context.Context, id string) (Profile, error) {
	row := q.db.QueryRowContext(ctx, getProfile, id)
	var i Profile
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Description,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getTokenByLookup = `-- name: GetTokenByLookup :one
SELECT id, kind, subject_id, lookup, secret_hash, profile_ids, created_at, expires_at, used_at, revoked_at
FROM tokens WHERE lookup = ?
`

func (q *Queries) GetTokenByLookup(ctx context.Context, lookup string) (Token, error) {
	row := q.db.QueryRowContext(ctx, getTokenByLookup, lookup)
	var i Token
	err := row.Scan(
		&i.ID,
		&i.Kind,
		&i.SubjectID,
		&i.Lookup,
		&i.SecretHash,
		&i.ProfileIds,
		&i.CreatedAt,
		&i.ExpiresAt,
		&i.UsedAt,
		&i.RevokedAt,
	)
	return i, err
}

const heartbeatDevice = `-- name: HeartbeatDevice :execrows
UPDATE devices SET last_seen_at = ?, updated_at = ? WHERE id = ?
`

type HeartbeatDeviceParams struct {
	LastSeenAt *string
	UpdatedAt  string
	ID         string
}

func (q *Queries) HeartbeatDevice(ctx context.Context, arg HeartbeatDeviceParams) (int64, error) {
	result, err := q.db.ExecContext(ctx, heartbeatDevice, arg.LastSeenAt, arg.UpdatedAt, arg.ID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const insertAliasDevice = `-- name: InsertAliasDevice :exec
INSERT INTO alias_devices (alias_id, device_id) VALUES (?, ?)
`

type InsertAliasDeviceParams struct {
	AliasID  string
	DeviceID string
}

func (q *Queries) InsertAliasDevice(ctx context.Context, arg InsertAliasDeviceParams) error {
	_, err := q.db.ExecContext(ctx, insertAliasDevice, arg.AliasID, arg.DeviceID)
	return err
}

const insertAliasProfile = `-- name: InsertAliasProfile :exec
INSERT INTO alias_profiles (alias_id, profile_id) VALUES (?, ?)
`

type InsertAliasProfileParams struct {
	AliasID   string
	ProfileID string
}

func (q *Queries) InsertAliasProfile(ctx context.Context, arg InsertAliasProfileParams) error {
	_, err := q.db.ExecContext(ctx, insertAliasProfile, arg.AliasID, arg.ProfileID)
	return err
}

const insertDevice = `-- name: InsertDevice :exec
INSERT INTO devices (id, name, platform, shell, client_version, created_at, updated_at)
VALUES (?, ?, ?, ?, ?, ?, ?)
`

type InsertDeviceParams struct {
	ID            string
	Name          string
	Platform      string
	Shell         string
	ClientVersion string
	CreatedAt     string
	UpdatedAt     string
}

func (q *Queries) InsertDevice(ctx context.Context, arg InsertDeviceParams) error {
	_, err := q.db.ExecContext(ctx, insertDevice,
		arg.ID,
		arg.Name,
		arg.Platform,
		arg.Shell,
		arg.ClientVersion,
		arg.CreatedAt,
		arg.UpdatedAt,
	)
	return err
}

const insertDeviceProfile = `-- name: InsertDeviceProfile :exec
INSERT INTO device_profiles (device_id, profile_id) VALUES (?, ?)
`

type InsertDeviceProfileParams struct {
	DeviceID  string
	ProfileID string
}

func (q *Queries) InsertDeviceProfile(ctx context.Context, arg InsertDeviceProfileParams) error {
	_, err := q.db.ExecContext(ctx, insertDeviceProfile, arg.DeviceID, arg.ProfileID)
	return err
}

const listAliasDeviceIDs = `-- name: ListAliasDeviceIDs :many
SELECT device_id FROM alias_devices WHERE alias_id = ? ORDER BY device_id
`

func (q *Queries) ListAliasDeviceIDs(ctx context.Context, aliasID string) ([]string, error) {
	rows, err := q.db.QueryContext(ctx, listAliasDeviceIDs, aliasID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []string
	for rows.Next() {
		var device_id string
		if err := rows.Scan(&device_id); err != nil {
			return nil, err
		}
		items = append(items, device_id)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listAliasProfileIDs = `-- name: ListAliasProfileIDs :many
SELECT profile_id FROM alias_profiles WHERE alias_id = ? ORDER BY profile_id
`

func (q *Queries) ListAliasProfileIDs(ctx context.Context, aliasID string) ([]string, error) {
	rows, err := q.db.QueryContext(ctx, listAliasProfileIDs, aliasID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []string
	for rows.Next() {
		var profile_id string
		if err := rows.Scan(&profile_id); err != nil {
			return nil, err
		}
		items = append(items, profile_id)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listAliases = `-- name: ListAliases :many
SELECT id, name, command, description, enabled, platforms, shells, tags, created_at, updated_at
FROM aliases ORDER BY name
`

func (q *Queries) ListAliases(ctx context.Context) ([]Alias, error) {
	rows, err := q.db.QueryContext(ctx, listAliases)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Alias
	for rows.Next() {
		var i Alias
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Command,
			&i.Description,
			&i.Enabled,
			&i.Platforms,
			&i.Shells,
			&i.Tags,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listDeviceProfileIDs = `-- name: ListDeviceProfileIDs :many
SELECT profile_id FROM device_profiles WHERE device_id = ? ORDER BY profile_id
`

func (q *Queries) ListDeviceProfileIDs(ctx context.Context, deviceID string) ([]string, error) {
	rows, err := q.db.QueryContext(ctx, listDeviceProfileIDs, deviceID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []string
	for rows.Next() {
		var profile_id string
		if err := rows.Scan(&profile_id); err != nil {
			return nil, err
		}
		items = append(items, profile_id)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listDevices = `-- name: ListDevices :many
SELECT id, name, platform, shell, client_version, created_at, updated_at, last_seen_at, last_sync_at, revoked_at
FROM devices ORDER BY name
`

func (q *Queries) ListDevices(ctx context.Context) ([]Device, error) {
	rows, err := q.db.QueryContext(ctx, listDevices)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Device
	for rows.Next() {
		var i Device
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Platform,
			&i.Shell,
			&i.ClientVersion,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.LastSeenAt,
			&i.LastSyncAt,
			&i.RevokedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listProfiles = `-- name: ListProfiles :many
SELECT id, name, description, created_at, updated_at FROM profiles ORDER BY name
`

func (q *Queries) ListProfiles(ctx context.Context) ([]Profile, error) {
	rows, err := q.db.QueryContext(ctx, listProfiles)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Profile
	for rows.Next() {
		var i Profile
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Description,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const revokeDevice = `-- name: RevokeDevice :execrows
UPDATE devices SET revoked_at = ?, updated_at = ? WHERE id = ?
`

type RevokeDeviceParams struct {
	RevokedAt *string
	UpdatedAt string
	ID        string
}

func (q *Queries) RevokeDevice(ctx context.Context, arg RevokeDeviceParams) (int64, error) {
	result, err := q.db.ExecContext(ctx, revokeDevice, arg.RevokedAt, arg.UpdatedAt, arg.ID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const revokeToken = `-- name: RevokeToken :execrows
UPDATE tokens SET revoked_at = ? WHERE id = ?
`

type RevokeTokenParams struct {
	RevokedAt *string
	ID        string
}

func (q *Queries) RevokeToken(ctx context.Context, arg RevokeTokenParams) (int64, error) {
	result, err := q.db.ExecContext(ctx, revokeToken, arg.RevokedAt, arg.ID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const revokeTokensBySubject = `-- name: RevokeTokensBySubject :exec
UPDATE tokens SET revoked_at = ? WHERE kind = ? AND subject_id = ? AND revoked_at IS NULL
`

type RevokeTokensBySubjectParams struct {
	RevokedAt *string
	Kind      string
	SubjectID string
}

func (q *Queries) RevokeTokensBySubject(ctx context.Context, arg RevokeTokensBySubjectParams) error {
	_, err := q.db.ExecContext(ctx, revokeTokensBySubject, arg.RevokedAt, arg.Kind, arg.SubjectID)
	return err
}

const touchDevice = `-- name: TouchDevice :execrows
UPDATE devices SET platform = ?, shell = ?, last_seen_at = ?, last_sync_at = ?, updated_at = ? WHERE id = ?
`

type TouchDeviceParams struct {
	Platform   string
	Shell      string
	LastSeenAt *string
	LastSyncAt *string
	UpdatedAt  string
	ID         string
}

func (q *Queries) TouchDevice(ctx context.Context, arg TouchDeviceParams) (int64, error) {
	result, err := q.db.ExecContext(ctx, touchDevice,
		arg.Platform,
		arg.Shell,
		arg.LastSeenAt,
		arg.LastSyncAt,
		arg.UpdatedAt,
		arg.ID,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const updateAlias = `-- name: UpdateAlias :one
UPDATE aliases
SET name = ?, command = ?, description = ?, enabled = ?, platforms = ?, shells = ?, tags = ?, updated_at = ?
WHERE id = ?
RETURNING id, name, command, description, enabled, platforms, shells, tags, created_at, updated_at
`

type UpdateAliasParams struct {
	Name        string
	Command     string
	Description string
	Enabled     int64
	Platforms   string
	Shells      string
	Tags        string
	UpdatedAt   string
	ID          string
}

func (q *Queries) UpdateAlias(ctx context.Context, arg UpdateAliasParams) (Alias, error) {
	row := q.db.QueryRowContext(ctx, updateAlias,
		arg.Name,
		arg.Command,
		arg.Description,
		arg.Enabled,
		arg.Platforms,
		arg.Shells,
		arg.Tags,
		arg.UpdatedAt,
		arg.ID,
	)
	var i Alias
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Command,
		&i.Description,
		&i.Enabled,
		&i.Platforms,
		&i.Shells,
		&i.Tags,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const updateDevice = `-- name: UpdateDevice :execrows
UPDATE devices SET name = ?, updated_at = ? WHERE id = ?
`

type UpdateDeviceParams struct {
	Name      string
	UpdatedAt string
	ID        string
}

func (q *Queries) UpdateDevice(ctx context.Context, arg UpdateDeviceParams) (int64, error) {
	result, err := q.db.ExecContext(ctx, updateDevice, arg.Name, arg.UpdatedAt, arg.ID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const updateProfile = `-- name: UpdateProfile :one
UPDATE profiles SET name = ?, description = ?, updated_at = ?
WHERE id = ?
RETURNING id, name, description, created_at, updated_at
`

type UpdateProfileParams struct {
	Name        string
	Description string
	UpdatedAt   string
	ID          string
}

func (q *Queries) UpdateProfile(ctx context.Context, arg UpdateProfileParams) (Profile, error) {
	row := q.db.QueryRowContext(ctx, updateProfile,
		arg.Name,
		arg.Description,
		arg.UpdatedAt,
		arg.ID,
	)
	var i Profile
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Description,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
