package renderers

import (
	"fmt"
	"strings"

	"github.com/angeltonio/aliasdeck/internal/domain"
)

// writeHeader emits the banner at the top of every generated file.
//
// The comment marker is a parameter because PowerShell will want `#` too but a
// future renderer may not, and the header is otherwise identical everywhere.
//
// Note what is absent: a timestamp. Rendered output must be byte-deterministic
// so that an unchanged configuration produces an unchanged file and sync can
// skip the write entirely. "Generated at 14:32" would make every single sync
// look like a change, which turns a dotfiles repository into a stream of empty
// commits. When the file was written belongs in local sync state, not in the
// file itself.
func writeHeader(b *strings.Builder, comment string, cfg domain.ResolvedConfig, count int) {
	line := func(format string, args ...any) {
		b.WriteString(comment)
		if format != "" {
			b.WriteString(" ")
			fmt.Fprintf(b, format, args...)
		}
		b.WriteString("\n")
	}

	line("Generated by AliasDeck. Do not edit.")
	line("")

	if name := sanitizeComment(cfg.Device.Name); name != "" {
		line("Device:   %s (%s / %s)", name, cfg.Device.Platform, cfg.Device.Shell)
	} else {
		line("Device:   %s / %s", cfg.Device.Platform, cfg.Device.Shell)
	}

	revision := cfg.Revision
	if revision == "" {
		revision = "(unknown)"
	}
	line("Revision: %s", revision)
	line("Aliases:  %d", count)

	line("")
	line("Changes made to this file are lost on the next `aliasdeck sync`.")
	line("Edit your aliases.yaml, or use the AliasDeck web UI.")
}
