package renderers

import (
	"strconv"
	"strings"
	"unicode"

	"github.com/angeltonio/aliasdeck/internal/domain"
	"github.com/angeltonio/aliasdeck/internal/validate"
)

const (
	legacyHeaderLine        = "# Generated by AliasDeck. Do not edit."
	legacyChangesLine       = "# Changes made to this file are lost on the next `aliasdeck sync`."
	legacyEditLine          = "# Edit your aliases.yaml, or use the AliasDeck web UI."
	managedAliasesGuardLine = "if [ -n \"${ALIASDECK_MANAGED_ALIAS_NAMES-}\" ]; then\n"
	legacyMigrationPrefix   = "if [ -z \"${ALIASDECK_MANAGED_ALIAS_NAMES+x}\" ]; then\n  ALIASDECK_MANAGED_ALIAS_NAMES="
	legacyMigrationSuffix   = "\nfi\n"
)

// MigrateLegacyPOSIXOutput carries the alias names from an exact pre-v0.5.4
// AliasDeck-generated POSIX file into the current generated file. The shell
// can then remove aliases that were loaded before managed-name tracking
// existed. Previous content is parsed as inert bytes and is never sourced or
// evaluated.
func MigrateLegacyPOSIXOutput(current string, previous []byte, shell domain.Shell) string {
	if shell != domain.ShellBash && shell != domain.ShellZsh {
		return current
	}

	names, ok := parseLegacyPOSIXAliases(string(previous), shell)
	if !ok || len(names) == 0 {
		return current
	}
	return injectLegacyMigration(current, names)
}

// CarryForwardLegacyPOSIXMigration carries a marker from a current generated
// file into its successor. The caller must first prove previous matches the
// output hash in AliasDeck's state; unlike the strict legacy parser above,
// the marker alone is not authority to remove aliases from a user's shell.
func CarryForwardLegacyPOSIXMigration(current string, previous []byte, shell domain.Shell) string {
	if shell != domain.ShellBash && shell != domain.ShellZsh {
		return current
	}
	names, ok := parseCurrentLegacyMigration(string(previous), shell)
	if !ok {
		return current
	}
	return injectLegacyMigration(current, names)
}

func injectLegacyMigration(current string, names []string) string {
	needle := "\n" + managedAliasesGuardLine
	if !strings.Contains(current, needle) {
		return current
	}
	block := "\n" + legacyMigrationPrefix + quotePOSIX(strings.Join(names, " ")) + legacyMigrationSuffix
	return strings.Replace(current, needle, block+managedAliasesGuardLine, 1)
}

func parseLegacyPOSIXAliases(contents string, shell domain.Shell) ([]string, bool) {
	if contents == "" || strings.Contains(contents, "\r") || !strings.HasSuffix(contents, "\n") {
		return nil, false
	}
	lines := strings.Split(contents, "\n")
	if len(lines) < 9 || lines[len(lines)-1] != "" {
		return nil, false
	}
	if lines[0] != legacyHeaderLine || lines[1] != "#" ||
		!validLegacyDeviceLine(lines[2], shell) || !validLegacyRevisionLine(lines[3]) ||
		lines[5] != "#" || lines[6] != legacyChangesLine || lines[7] != legacyEditLine {
		return nil, false
	}

	count, ok := parseLegacyAliasCount(lines[4])
	if !ok {
		return nil, false
	}

	names := make([]string, 0, count)
	i := 8
	for len(names) < count {
		if i >= len(lines)-1 || lines[i] != "" {
			return nil, false
		}
		i++
		if i < len(lines)-1 && strings.HasPrefix(lines[i], "# ") {
			if !validLegacyDescription(strings.TrimPrefix(lines[i], "# ")) {
				return nil, false
			}
			i++
		}
		if i >= len(lines)-1 {
			return nil, false
		}
		name, ok := parseLegacyAliasLine(lines[i], shell)
		if !ok || (len(names) > 0 && names[len(names)-1] >= name) {
			return nil, false
		}
		names = append(names, name)
		i++
	}

	if i != len(lines)-1 || lines[i] != "" {
		return nil, false
	}
	return names, true
}

func validLegacyDeviceLine(line string, shell domain.Shell) bool {
	const prefix = "# Device:   "
	if !strings.HasPrefix(line, prefix) || hasControl(strings.TrimPrefix(line, prefix)) {
		return false
	}
	want := " / " + shell.String()
	return strings.HasSuffix(line, want) || strings.HasSuffix(line, want+")")
}

func validLegacyRevisionLine(line string) bool {
	const prefix = "# Revision: "
	revision := strings.TrimPrefix(line, prefix)
	if len(revision) != 12 || prefix+revision != line {
		return false
	}
	for _, r := range revision {
		if !((r >= '0' && r <= '9') || (r >= 'a' && r <= 'f')) {
			return false
		}
	}
	return true
}

func parseLegacyAliasCount(line string) (int, bool) {
	const prefix = "# Aliases:  "
	raw := strings.TrimPrefix(line, prefix)
	if raw == "" || prefix+raw != line || (len(raw) > 1 && raw[0] == '0') {
		return 0, false
	}
	count, err := strconv.Atoi(raw)
	return count, err == nil && count >= 0 && count <= validate.MaxAliases
}

func validLegacyDescription(description string) bool {
	return description != "" && strings.TrimSpace(description) == description && !hasControl(description)
}

func parseLegacyAliasLine(line string, shell domain.Shell) (string, bool) {
	const prefix = "alias "
	if !strings.HasPrefix(line, prefix) {
		return "", false
	}
	name, rhs, found := strings.Cut(strings.TrimPrefix(line, prefix), "=")
	if !found || validate.Name(name, shell) != nil {
		return "", false
	}
	command, ok := decodeQuotedPOSIX(rhs)
	if !ok || validate.Command(command) != nil {
		return "", false
	}
	return name, true
}

func decodeQuotedPOSIX(value string) (string, bool) {
	if len(value) < 2 || value[0] != '\'' || value[len(value)-1] != '\'' {
		return "", false
	}
	decoded := strings.ReplaceAll(value[1:len(value)-1], `'\''`, `'`)
	return decoded, quotePOSIX(decoded) == value
}

func hasControl(value string) bool {
	for _, r := range value {
		if unicode.IsControl(r) {
			return true
		}
	}
	return false
}

func parseCurrentLegacyMigration(contents string, shell domain.Shell) ([]string, bool) {
	start := strings.Index(contents, legacyMigrationPrefix)
	if start < 0 || strings.Count(contents, legacyMigrationPrefix) != 1 {
		return nil, false
	}
	start += len(legacyMigrationPrefix)
	end := strings.Index(contents[start:], legacyMigrationSuffix+managedAliasesGuardLine)
	if end < 0 {
		return nil, false
	}
	raw := contents[start : start+end]
	decoded, ok := decodeQuotedPOSIX(raw)
	if !ok || decoded == "" {
		return nil, false
	}
	names := strings.Fields(decoded)
	if strings.Join(names, " ") != decoded {
		return nil, false
	}
	for i, name := range names {
		if validate.Name(name, shell) != nil || (i > 0 && names[i-1] >= name) {
			return nil, false
		}
	}
	return names, true
}
